const SETTINGS_DIR_NAME = '.jiminy'
const SETTINGS_FILE_NAME = 'settings.json'
const JIMINY_BEHIND_THE_SCENES_DIR_NAME = 'jiminy'
const CAPTURES_DIR_NAME = 'jiminy-captures'
const JIMINY_ANALYSIS_DIR_NAME = 'analysis'
const RECORDINGS_DIR_NAME = 'recordings'
const CAPTURE_FILENAME_PREFIX = ''

module.exports = {
  SETTINGS_DIR_NAME,
  SETTINGS_FILE_NAME,
  JIMINY_BEHIND_THE_SCENES_DIR_NAME,
  CAPTURES_DIR_NAME,
  JIMINY_ANALYSIS_DIR_NAME,
  RECORDINGS_DIR_NAME,
  CAPTURE_FILENAME_PREFIX
}
